default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"] %>
  <% else %>
  database: rails_chat_development
  <% end %>

test:
  <<: *default
  database: rails_chat_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
